### ISSUE TITLE
Map POIs under map...

### ISSUE THREAD

**Issue by IrcDirk** [mikepauer/Carbonite#16]
@mikepauer something is wrong with map pois after your changes:

on minimap they are like behind map

![obraz](http://i.imgur.com/2qzJ7K3.png)

on maximized they are not shown at all

![obraz](http://i.imgur.com/WkD7nYS.png)

nodes and quest arrow is also under map

![obraz](https://user-images.githubusercontent.com/1030023/27772069-ab5299ce-5f5b-11e7-8d4e-13d602d1e614.png)

This happens after some time of questing, reload doesnt fix this, need to close and open game again.
I could search fix for this, but this would take much more time, as u now better what did u changed.

**Comment by IrcDirk** [comment]
Also going back to city (like Orgrimmar) fixes temporary this issue.

**Comment by fdellwing** [comment]
Can confirm that. Also just had the case, that all WQ Icons where missing until relogging.

**Comment by IrcDirk** [comment]
Yep. Scrolling away to show minimap docked then zoom in again fixes this issue. Doesnt have time to fix this.

**Comment by IrcDirk** [comment]
@mikepauer can u check if this fix didnt broke something else? I did test this for a week and found no disadvantages but...

**Comment by mikepauer** [comment]
Fix should be fine, as soon as I saw what you guys were describing in game myself It confirmed to me that it was the frame level too low and it appeared to be "under" the map because of transparency. 

I run with transparency high on most things so when I saw it, it wasn't dissapearing under the map but instead showing but very faded.

**Comment by Basman1969** [comment]
Thank you for your prompt response

On Friday, July 14, 2017, 1:17:24 PM EDT, mikepauer <notifications@github.com> wrote:


Fix should be fine, as soon as I saw what you guys were describing in game myself It confirmed to me that it was the frame level too low and it appeared to be "under" the map because of transparency.
