### ISSUE TITLE
[ADDON_ACTION_BLOCKED Retail 11.0.0.11

### ISSUE THREAD

**Issue by GeoRam2016** [mikepauer/Carbonite#278]
Hi
This bug always occurs when I fight.

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' hat versucht die geschützte Funktion 'Button:SetPassThroughButtons()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:158>
[string "=[C]"]: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:97: in function <...haredMapDataProviders/BonusObjectiveDataProvider.lua:92>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: in function `accessor'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:60: in function `AddCancelableCallback'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:92: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/BonusObjectiveDataProvider.lua"]:65: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:148: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:147>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by GeoRam2016** [comment]
Is this no Bug?

**Comment by IrcDirk** [comment]
Hmmm cant simulate this error. What are u doing when this happens? What are u clicking while in combat?

**Comment by qlesz** [comment]
i am getting that error too sometimes
it look like it's random and i think it's associated with bug grabber more than  carbonite itself, because i get very similair error for bartender aswell with exacly the same line call in bug grabber (485) with both of that errors.
17x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:229: in function `AddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:163: in function `CheckAddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:174: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:41: in function <...lizzard_SharedMapDataProviders/QuestDataProvider.lua:41>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_FrameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua"]:59: in function `CacheCurrentSuperTrackInfo'
[string "@Blizzard_FrameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua"]:17: in function <...rameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua:15>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by IrcDirk** [comment]
Cant reproduce and cant find a fault in Carbonite.

**Comment by GeoRam2016** [comment]
Hi
I don't know which buttons to press to get the error.
I play Beastmaster Hunter and inFight it comes up. Not always though.
It either comes up in normal combat or in the dungeon. That's when it's at its worst.

**Comment by Thrumbar** [comment]
This error has been reported with several addons.  Bag, map and others.  I get it on occasion using Enhanced Battlefield Map addon and Bagnon.

**Comment by IrcDirk** [comment]
Fixed ;)
