### ISSUE TITLE
cannot use/drink from flask in Quest Watch Window

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#398]
Doing "When Dreams become Nightmares" quest and the flask icon beside the quest in the watch windows in unresponsive..

**Comment by IrcDirk** [comment]
U have to click multiple times on icon to make it work, so this is still an issue that must be fixed.

**Comment by Rythal** [comment]
'I've been looking into this one... if you open the real blizzard map, all buttons/items in the watch work, the moment it's closed, they stop working again.... but I haven't figured out why.

**Comment by IrcDirk** [comment]
@Rythal can u point me to function which is used when we clicking on this icons?

**Comment by Rythal** [comment]
There isn't a function Carbonite calls... we are creating the same buttons the blizzard objective tracker does because it's entirely "secure protected" now to stop automation. It seems they are doing something now to stop the clicks if questlog/tracker isn't visible, if you click a million times it works randomly, or if you have the blizzard quest window (map) open it works.

**Comment by IrcDirk** [comment]
After recent commits everything works fine now.

**Comment by IrcDirk** [comment]
Ok i know why this is happening: when we have "Watch delay time" set to low value like 50ms, quest watch window refreshes 50ms so buttons are drawn and cleared many times per secound and some time in between we cant click on them. Setting "Watch delay time" to 250ms make it work like it should.
