### ISSUE TITLE
Quests files update? (lua files)

### ISSUE THREAD

**Issue by IrcDirk** [mikepauer/Carbonite#470]
I have updated my database of quests (mainly from wowhead db). Now i can generate new files with quests info, blobs etc. 

But problem is with those quest 91-100 that was edited by hand by some other users. They will be overwritten.

So now i dont know what should i do... What do u think?

**Comment by JWMcQuire** [comment]
I did the Demon Hunter starter area as I played verifying with wowhead where the quests were available. Some of the Pre-Legion quests weren't available on wowhead, so I used wowdb which only helped a little except that their npc id's were different than what I got using an add on called "AlltheIds" which agreed with wowhead's npc ids.

I don't remember which one, but one of the pre-Legion or DH quests was listed on wowhead 3 times with different id numbers, but Carbonite showed the actual id numbers which I used to add that quest for each side leaving the third one out.

Beyond that, on the a few of the quests I used wowhead for verification, the map coordinates may be different because Wowhead's were off by more than just 100 yards compared to where my alt was standing when I checked with Wowhead.

Also, for the WoD quests including Tanaan, Blizzard's own system made it necessary to force more accurate data on some quests using objective lines or duplicating a couple of neutral quests in Tanaan  because they had the same quest npc (Quest #39433 - Unseen Influence) located in the separate faction areas for its dailies.

As far as overwriting, I would assume that unless your just replacing the whole file, that you can do a compare and see if there are any conflicts. If there aren't any conflicts, then the new edits from Wowhead should be mergeable. If there are any conflicts, then I would expect you and Mike to decide whether or not to overwrite. I don't know how much data would be lost or changed, but I would expect that the hand-edited data could be re-merged with new pulls later to re-add or "correct" data that was lost or inaccurate.

So if you overwrite, since my database is up-to-date with the master, I could do a new compare and make a pull request to re-add any data that might be lost in the overwrite. Hopefully it would be that simple but since I'm still learning, I won't hold my breath.

**Comment by mikepauer** [comment]
I have the original generated file from December 2014 still, so it's relatively easy to do a diff between it and today's file to find exactly which changes have been made

**Comment by IrcDirk** [comment]
Ok, so i will upload those files. They are whole new generted files.

**Comment by JWMcQuire** [comment]
So I assume then that I should then compare my branch when the new file is uploaded to see if any of my edits from the last year might be usable?

**Comment by IrcDirk** [comment]
I first upload 0 to 90. Then will see.

**Comment by IrcDirk** [comment]
OK uploaded 0, 91-100, and 101-110... but those are only generated files from wowhead data.

**Comment by IrcDirk** [comment]
Files updated. NPCs also. Closing.
