### ISSUE TITLE
7.1 work in progress...

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#558]
Made it all caps, because I am very unhappy.  I am testing a ptr fork of the most recent carbonite, and the fix for the api changes appears to be very involved.  UnitName(unit) returned nils, when unit = "party" so, trap for nil and set unit = "player". to avoid the error.  How do I give someone access to my new branch on my fork, to allow more testing.  Admittedly, I only run Carbonite, Quests, Notes, and Warehouse, but as of this notes date and time, I am running around with no LUA errors in those modules, in any zones.

My excitement is short lived, no quests showing in carbonite quest log, just blizzard log.  No error messages, so I will investigate further.

WorldMapPlayerLower returns nil, commented out for now just to test

maps appear to have changed completely, none of the instance maps, even on old content, would load.  throwing all kinds of errors.  No carbonite quest log, and worldquestmap errors, so that whole block is commented out.

**Comment by IrcDirk** [comment]
Read what i wrote in other PTR "issues". Read API changes to know why those NIL happens and when.

**Comment by samyonair** [comment]
We Can downlaod your PTR Branch to test, the Problem is to point it out Blizz wants no break all possibilities to draw arrows or other tools in PVP, Dungeons and Raids 

for my Personal meaning in combat state nil would help but thats Blizz Policy and we have to deal with it

we should make a Roadmap how to deal with it, which functions can be there and what we cannot do anymore

**Comment by IrcDirk** [comment]
Im downloading now. My idea is to overwrite blizz functions those that return NIL to return X = 0 and Y = 0. But first ill need to run PTR to see what other problems we might have.

**Comment by SteveEbey73742** [comment]
commenting was just to show what was broken, and let me run tests, without a screen full of errors, to see what still works.

**Comment by IrcDirk** [comment]
Ill talk with Rythal o make PTR branch. I have my own fixes ;) We need to work together.

**Comment by samyonair** [comment]
Good Idea, we need to work on it, an Idea would be a Ptr branch only if PTR is Open and push it to master after release of state remove the Branch not as last time with to developed branches with diffs and conflicts

greetings Samyonair

**Comment by IrcDirk** [comment]
Got working Map and Quest Module... not so bad ;) Waiting on PTR branch to push my fixes.

**Comment by mikepauer** [comment]
Done.

**Comment by IrcDirk** [comment]
Ok pushed my fixes to 7.1 branch... Carbonite works quite well but need more testing.

**Comment by SteveEbey73742** [comment]
deleted my fork, and re forked, to match what you have on here.

**Comment by IrcDirk** [comment]
Changed title of tis issue ;)

**Comment by SteveEbey73742** [comment]
went in stockades, maps worked fine. questing seems to be good also.  Ran new content on broken isles, found no problems.  Granted, I am only running Carb Maps, notes, quests, and warehouse.  I do not pvp, so do not have social installed. Warehouse still times out if used, with script ran too long.

**Comment by IrcDirk** [comment]
Warehouse works fine on my side... no problems.

**Comment by SteveEbey73742** [comment]
After I highlight all characters, at top of form, and search for an item.  3 to 5 minutes after I close warehouse, the script ran too long message appears.  does not matter the search term used, or even if it finds the items, once I close warehouse, the script ran too long comes up.

**Comment by IrcDirk** [comment]
In 7.0.3 that was fine?

**Comment by samyonair** [comment]
Just an Idea and a question on Posibility because map in dungeons isn't working with no Pos Data would there be a way to just put blizz maps into carbonite with a iframe?

My Idea if pos data Nil iframe blizz map instead of carbonite map don't know if this is possible but would be a better solution on large dungeons with many floors to see Position and look up 

same for PVP

that would break scroling but better then to see me on pos 0.0 

It is only an Idea to discuss without knowing posibility

**Comment by IrcDirk** [comment]
Yes ... i was thinking the same, make Blizz minimap 100% width and height in dungs and bgs if combined with Carbonite map.

**Comment by samyonair** [comment]
then we should do both I don't use combined 
if combind use blizzminimap like other minimap tools do and Map if not combind because I use most times to lookup next boss on map (forget sometimes pos in old doungeons)

**Comment by IrcDirk** [comment]
Ok, ill do the combined part ;)

**Comment by samyonair** [comment]
I think about how to do it with blizz map but their for must learn a bit^^

**Comment by IrcDirk** [comment]
Try... ask if u dont know something.

**Comment by samyonair** [comment]
yes will do, will try with existing code i have seen comented out

**Comment by samyonair** [comment]
Have done some reading so far, 

we will need some more information for the new ways.

There are new ways to access units on the map:
"AddUnit",
"AddUnitFileID",
"AddUnitAtlas",
"ClearUnits",
"FinalizeUnits", It's illegal to call AddUnit after a call to Finalize in the same frame that this was finalized.
"SetPlayerPingTexture",
"StartPlayerPing",
"StopPlayerPing",
"GetMouseOverUnits",
"SetOverrideMapID",
"GetOverrideMapID", 

because as i read on https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/WorldMapFrame.lua 

but for me this will be a long term project to understand all

**Comment by IrcDirk** [comment]
http://eu.battle.net/forums/en/wow/topic/17613473893

> (...) Unit Position changes
> 
> Several unit positioning/facing/range APIs have been restricted so that they will only return valid values when the following criteria are met:
> • Unit is the active player or in the party
> • Unit is not in any kind of instance PvE or PvP.
> 
> The following functions have been affected:
> GetPlayerMapPosition
> UnitCameraFacing
> UnitDistanceSquared
> UnitFacing
> UnitPosition (note: when in the restricted state, the mapID return is still valid)
> 
> There are new ways to access units on the map:
> "AddUnit",
> "AddUnitFileID",
> "AddUnitAtlas",
> "ClearUnits",
> "FinalizeUnits", It's illegal to call AddUnit after a call to Finalize in the same frame that this was finalized.
> "SetPlayerPingTexture",
> "StartPlayerPing",
> "StopPlayerPing",
> "GetMouseOverUnits",
> "SetOverrideMapID",
> "GetOverrideMapID", (...)

To get Unit position u need to use **UnitPosition** and as u can see in this is also restricted to instances. So there is NO way to find out the position in instances/bgs.

**Comment by IrcDirk** [comment]
As to maps in instances @mikepauer can we add blizz quests POIs? Its easier to see them on map than using alt-M ;)
