### ISSUE TITLE
Map not showing pary/raid members

### ISSUE THREAD

**Issue by DarrenWillows** [mikepauer/Carbonite#610]
Map is not showing party or raid members in PVP Battlegrounds.
I am using head build at present.

**Comment by IrcDirk** [comment]
Right click on map check "Show instance map".

**Comment by DarrenWillows** [comment]
This never used to be the case.
You could see the people on the map and also had the Tracking HUD in PVP linking up to the players on the standard map, without "Show Instance Map".
Has something changed stopping this functionality from happening?

**Comment by mikepauer** [comment]
Yes something changed.. in 7.1 blizzard changed all battlegrounds and instances to no longer provide player locations and it's still being worked on to have both the markers and vechicles and the new player locations. 

Some things like the tracking HUD will never work again since it always returns 0,0 now as a location for people.

**Comment by IrcDirk** [comment]
@DarrenWillows please read 7.1 API changes: https://us.battle.net/forums/en/wow/topic/20749494846
